Repository gip-inclusion/immersion-facile, pull requests merged in 2023-05, with the labels that each got.

#39 Feature / rm Paragraph / Bold / Title / SubTitle
  front/src/app/components/search/ContactModalContent.tsx
  libs/react-design-system/src/immersionFacile/components/text/Colored.stories.tsx
  libs/react-design-system/src/immersionFacile/components/text/Colored.tsx
  libs/react-design-system/src/immersionFacile/components/text/SubTitle.stories.tsx
  libs/react-design-system/src/immersionFacile/components/text/SubTitle.tsx
  libs/react-design-system/src/immersionFacile/components/text/Title.stories.tsx
  libs/react-design-system/src/immersionFacile/components/text/Title.tsx
  libs/react-design-system/src/immersionFacile/components/text/index.ts
Labels: Ready for review

#68 Fix/mini stage cci wording
  front/src/app/components/forms/convention/sections/immersion-conditions/ImmersionConditionsCommonFields.tsx
  front/src/app/contents/forms/convention/formConvention.ts
  front/src/app/contents/forms/convention/textSetup.tsx
  front/src/app/pages/convention/ConventionDocumentPage.tsx
  shared/src/email/defaultConventionFinalLegals.ts
  shared/src/email/templatesByName.ts
Labels: Ready for review

#137 validate addressGateway manual tests
  back/src/adapters/secondary/addressGateway/HttpAddressGateway.manual.test.ts
Labels: TECH

#159 emailable add unavailable_smtp reason
  front/src/app/components/forms/commons/EmailValidationInput.tsx
  shared/src/email/validateEmail.dto.ts
Labels: bug

#164 add cep operator option to agency kind
  front/src/app/components/forms/agency/AgencyFormCommonFields.tsx
  shared/src/agency/agency.dto.ts
Labels: Ready for review

#172 add link to partner website in search results
  front/src/app/components/search/ContactModalContent.tsx
  front/src/app/components/search/SearchResult.tsx
Labels: Ready for review

#204 no notify throw on Pe adapter
  back/src/adapters/secondary/immersionOffer/poleEmploi/HttpPoleEmploiGateway.ts
Labels: TECH

#201 195 révision de ce qui est affichée dans la convention pour satisfaire la dgefp part2
  front/src/app/pages/convention/ConventionDocumentPage.tsx
Labels: Ready for review
