Repository gip-inclusion/immersion-facile, pull requests merged in 2023-07, with the labels that each got.

#408 fix rapport de synchronisation des conventions avec pe
  back/src/adapters/primary/scripts/triggerResyncOldConventionsToPe.ts
Labels: bug, Ready for review

#414 disable filed when department not selected
  front/src/app/components/forms/convention/sections/agency/AgencySelector.tsx
Labels: Ready for review

#430 add db logging for troubleshooting
  back/src/adapters/secondary/pg/PgAgencyRepository.ts
  back/src/adapters/secondary/pg/PgNotificationRepository.ts
  back/src/adapters/secondary/pg/PgOutboxRepository.ts
Labels: TECH

#443 discussions without exchanges
  back/src/_testBuilders/DiscussionAggregateBuilder.ts
  back/src/adapters/secondary/pg/PgDiscussionAggregateRepository.integration.test.ts
  back/src/adapters/secondary/pg/PgDiscussionAggregateRepository.ts
  back/src/adapters/secondary/pg/migrations/1688998172946_discussion-change-contract-mode-name.ts
  back/src/domain/immersionOffer/entities/DiscussionAggregate.ts
  back/src/domain/immersionOffer/useCases/ContactEstablishment.ts
  back/src/domain/immersionOffer/useCases/ContactEstablishment.unit.test.ts
  back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.ts
  back/src/domain/immersionOffer/useCases/notifications/NotifyContactRequest.unit.test.ts
  shared/src/discussion/discussion.dto.ts
  shared/src/formEstablishment/FormEstablishment.dto.ts
  shared/src/typeGuard.ts
Labels: bug, mise en relation

#444 fix 400 when submit contact establishment again
  front/src/app/components/search/ContactByEmail.tsx
  front/src/app/components/search/ContactByPhone.tsx
  front/src/app/components/search/ContactInPerson.tsx
  front/src/app/components/search/usePotentialBeneficiaryValues.ts
Labels: Ready for review

#471 modifier l'âge minimum pour demande mini stage cci 14ans -> 10ans
  shared/src/convention/ConventionDto.unit.test.ts
  shared/src/convention/convention.dto.ts
Labels: Ready for review

#479 fix rename migration file
  back/src/adapters/secondary/pg/migrations/1689774100000_add-additional-columns-to-feature-flags.ts
Labels: Ready for review
