Repository gip-inclusion/immersion-facile, pull requests merged in 2023-06, with the labels that each got.

#209 update convention reminder schedule
  back/scalingo/cron.json
Labels: TECH

#210 add ADR on repo
  doc/adr/2023-02-28-feedback-in-front.md
  doc/adr/2023-04-25-dev-process-PR.md
  doc/adr/dev-process-PR.md
  doc/adr/dev-team-organisation.md
  doc/adr/front/feedback-in-front.md
  doc/adr/front/front-code-organisation.md
  doc/adr/infra/infrastructure-provider.md
  doc/adr/pe.io/rome3-to-rome4.md
  doc/adr/query/metabase.md
  doc/adr/test/adapters-automated-integration-testing.md
Labels: TECH

#223 temporary email fix bad regex on zod release
  shared/src/email/email.schema.ts
  shared/src/email/email.unit.test.ts
  shared/src/email/validateEmail.dto.ts
  shared/src/zodUtils.ts
Labels: bug, TECH

#338 fix update establishment from siren script, to treat up to maxEstablishments per fullRun
  back/src/domain/immersionOffer/useCases/UpdateEstablishmentsFromSirenApiScript.ts
Labels: Ready for review

#331 rework gateways
  back/src/_testBuilders/buildTestApp.ts
  back/src/adapters/primary/config/appConfig.ts
  back/src/adapters/primary/config/createGateways.ts
  back/src/adapters/primary/scripts/updateAllPEAgenciesFromPeAgencyReferential.ts
  back/src/adapters/secondary/core/CachingAccessTokenGateway.ts
  back/src/adapters/secondary/core/InMemoryCachingGateway.ts
  back/src/adapters/secondary/core/InMemoryCachingGateway.unit.test.ts
  back/src/adapters/secondary/documentGateway/NotImplementedDocumentGateway.ts
  back/src/adapters/secondary/documentGateway/S3DocumentGateway.ts
  back/src/adapters/secondary/immersionOffer/InMemoryAccessTokenGateway.ts
  back/src/adapters/secondary/immersionOffer/PoleEmploiAccessTokenGateway.ts
  back/src/adapters/secondary/immersionOffer/inMemoryEstablishmentGroupRepository.ts
  back/src/adapters/secondary/immersionOffer/laBonneBoite/HttpLaBonneBoiteAPI.manual.test.ts
  back/src/adapters/secondary/immersionOffer/laBonneBoite/HttpLaBonneBoiteAPI.ts
  back/src/adapters/secondary/immersionOffer/peAgenciesReferential/HttpPeAgenciesReferential.manual.test.ts
  back/src/adapters/secondary/immersionOffer/peAgenciesReferential/HttpPeAgenciesReferential.ts
  back/src/adapters/secondary/immersionOffer/poleEmploi/HttpPoleEmploiGateway.ts
  back/src/adapters/secondary/poleEmploi/HttpPoleEmploiGateway.manual.test.ts
  back/src/adapters/secondary/poleEmploi/HttpPoleEmploiGateway.ts
  back/src/adapters/secondary/poleEmploi/InMemoryPoleEmploiGateway.ts
  back/src/adapters/secondary/poleEmploi/PoleEmploi.targets.ts
  back/src/domain/convention/ports/PoleEmploiGateway.ts
  back/src/domain/convention/useCases/ConventionsReminder.unit.test.ts
  back/src/domain/convention/useCases/broadcast/BroadcastToPoleEmploiOnConventionUpdates.unit.test.ts
  back/src/domain/core/ports/AccessTokenGateway.ts
Labels: TECH

#379 emphase modification reason in emails
  shared/src/email/emailTemplatesByName.ts
Labels: Ready for review

#381 modification d'un label du formulaire de mini-stage
  front/src/app/contents/forms/convention/formConvention.tsx
Labels: Ready for review, mini-stage

#384 sortir le nombre max de convention à synchroniser avec pe en variable d'environnement
  .env.sample
  back/src/adapters/primary/config/appConfig.ts
  back/src/adapters/primary/scripts/triggerResyncOldConventionsToPe.ts
Labels: Ready for review

#386 afficher le niveau d'études du bénéficiaire dans la page /pilotage-convention-admin
  front/src/app/contents/admin/conventionValidation.tsx
Labels: Ready for review

#393 log on generate shortlink for troubleshooting
  back/src/adapters/secondary/shortLinkIdGeneratorGateway/NanoIdShortLinkIdGeneratorGateway.ts
Labels: TECH

#394 modification de lien de téléchargement de bilan en bouton
  shared/src/email/emailTemplatesByName.ts
Labels: Ready for review

#396 ajouter un nouveau paragraph pour l'article 10 de la convention
  front/src/app/pages/convention/ConventionDocumentPage.tsx
Labels: Ready for review
