Repository gip-inclusion/immersion-facile, pull requests merged in 2024-03, with the labels that each got.

#1355 #1238 - Ajout d'un retour à l'utilisateur en cas de MER échouée (409)
  front/src/app/components/search/useContactEstablishmentError.ts
  shared/src/search/search.routes.ts
Labels: bug

#1359 #1360 - Mise à jour des données des formulaires de MER (par tel / en personne)
  front/src/app/components/immersion-offer/ContactByEmail.tsx
  front/src/app/components/immersion-offer/ContactByPhone.tsx
  front/src/app/components/immersion-offer/ContactInPerson.tsx
  front/src/app/components/immersion-offer/contactUtils.ts
Labels: bug

#1394 Suppression des extensions recommandés pour VSCode
  .vscode/extensions.json
Labels: TECH

#1436 #1435 - TECH mise à jour de la colonne "Type de structure" de la vue "View Conventions"
  back/src/config/pg/migrations/1711379976051_update-column-view-convention.ts
Labels: Mesure Impact
